zeus-transaction-storage:
  api:
    version: 1.0.0
server:
  port: 8086
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/transactionstoragedb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: transactionstorageapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: transactionstorageadmin
    password: password
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/transactionstorage.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


